### PR TITLE
Baxandall

### PR DESCRIPTION
**Pull request by TheseGoTo11**
A first pull request for discussion. I've added a passive "Baxandall" tone stack. The circuit is the same as the James, except the treble control only has one capacitor, which is connected at the treble potentiometer's wiper.

Sometimes I see "James vs. Baxendall" described as passive vs. active, and other times it's two caps on the treble control vs. one. If you'd rather call it a variation on the James you already have, or something else, that's ok with me. I do plan to also make an active version of this circuit.

I've included a PDF that shows the circuit analysis that I did before making the new maxima file. If it looks ok, perhaps a link could be added so that website users can read it. It was created in Apple Pages with latex equations, then exported as PDF.

The schematic image was created in KiCad, exported as SVG, then edited in Inkscape and exported as PNG. It has some colors and the background is transparent, so it looks a little different than the others. I could probably convert to greyscale and add a background if preferred.

The default component values are nearly the same as the existing James tone stack. I can't remember where I got the differences from. But these could be changed too.

### CODE REVIEW

**Comment by jatalahd** [comment]
Looks very nice! 

If you want to add a link to the circuit analysis file, it is OK for me. In your commit, you could add a new directory "circuit_analysis" and put the pdf there. Then add a relative link to ./circuit_analysis/<filename>.pdf. When I copy the files to the server, I will copy the circuit_analysis directory also, so the link would be preserved in the website. Please let me know if you want to add the link, or is the commit in this pull request fine as is. When you feel it is ready on your part, I will upload the latest version to the website. 

One thing that I have planned to do is to add a dropdown menu "more stacks" to the upmost linkbar, which would contain a vertical list of links to the stacks not fitting in the first line in the link bar. With the current amount of stacks, the layout will break into two lines and that takes room from the actual simulation view. Would you like to make this kind of refactoring, or will you leave that work to me? If you are not willing to do that, then I would do it after you have finished the active baxandall model.

**Comment by TheseGoTo11** [comment]
OK, I will move the circuit analysis PDF into its own directory as suggested. I need to commit an updated PDF anyway. Apple Pages wasn't handling a few equations quite right, so I have switched to a latex editor. And I'll figure out adding the link, though I'm not quite sure of the best location to display it on the page. Then I can have a look at doing the dropdown menu.

**Comment by jatalahd** [comment]
Your help is very much appreciated. I am attaching here an example (pdf, 2 pages) how you can proceed with the active baxandall stack. For op-amp as the active element, the analysis is very simple, but there is a rule of removing rows and columns which needs to be done and this is indicated in the attachment.

[baxa.pdf](https://github.com/jatalahd/tsc/files/6411352/baxa.pdf)

**Comment by TheseGoTo11** [comment]
OK, that looks great for the active denominator and then for the numerator it can reduce to 5x5 using the cofactor.
Vout=(Vin/Rin)*C(1,6) so then Vout/Vin=(-1/Rin)M(1,6)

What tool are you using to make the schematics? Maybe I can make mine to match the style. I think I should add R4 & R5 to the passive version. If a user doesn't want them then they can just set their resistances to zero.

Maybe I'll change my circuit analysis PDF to landscape too. That will make the matrices easier to read.

**Comment by jatalahd** [comment]
I am using the schematic editor from lepton-eda (earlier it was geda) ubuntu package. But your schematic is much better looking as it would take the visual aspect to another level. I don't mind if the styles are not matching.

**Comment by TheseGoTo11** [comment]
I'll work on the active Baxandall next. I wonder whether it might be nice to use a drop down menu to hold a variety of James/Baxandall circuits, as they get added. I can think of at least 8 variations.

Active vs passive
1 cap on treble vs 2 caps
1 cap on bass vs 2 caps

**Comment by jatalahd** [comment]
If you are going to add them all, then i guess some kind of menu would be good. Do it as you see best.

How do you want to proceed with this pull request, will you add all stacks under this and then I will merge to master or would you like to do separate pull requests?

Or would you like me to add you as a contributor , so you could just push directly to master when ever you like?

**Comment by TheseGoTo11** [comment]
I can do all the variations since the analysis will be so similar.  I don't know how long it will take to finish so I think it makes sense to pull this one in now. Adding as a contributor would be nice, instead of doing separate pull requests for each new one.  I can figure out how to put the variations into a menu.

**Comment by jatalahd** [comment]
Invite sent to you for collaborating in tsc repo. Hopefully that will give you full access to push your changes. I put this passive baxandall stack already live to the website. The circuit_analysis directory is also there, but there is no link yet. I think the links could fit nicely under the circuit image, to the same table cell.

**Comment by TheseGoTo11** [comment]
I was thinking the same thing about the circuit analysis link. I can go ahead and add that.

**Pull request merged**
